In [1]:
import pandas as pd
import numpy as np
import json
import ast

In [2]:
model_name = "../Results/DT"
sex = "Male"
task = "QBF"

path_results_summary = f"{model_name}/sex={sex}/task={task}/results_summary.csv"
path_outer_cv_results = f"{model_name}/sex={sex}/task={task}/outer_cv_results.csv"
path_inner_cv_results = f"{model_name}/sex={sex}/task={task}/inner_cv_results.csv"
path_resutls = f"{model_name}/sex={sex}/task={task}/results.csv"

df_results_summary = pd.read_csv(path_results_summary)
df_outer_cv_results = pd.read_csv(path_outer_cv_results)
df_inner_cv_results = pd.read_csv(path_inner_cv_results)
df_results = pd.read_csv(path_resutls)

In [3]:
df_results_summary

          Unnamed: 0      mean       std
0            roc_auc  0.526384  0.055066
1  balanced_accuracy  0.519352  0.042447
2  average_precision  0.362146  0.033799
3           f1_score  0.403838  0.058118

In [4]:
df_outer_cv_results

,repeat,outer_fold,roc_auc,balanced_accuracy,average_precision,f1_score
0,1,1,0.594523,0.556787,0.407297,0.422018
1,1,2,0.580601,0.542224,0.414754,0.410714
2,1,3,0.511632,0.485345,0.345060,0.330275
3,1,4,0.530059,0.494081,0.362718,0.316832
4,1,5,0.518868,0.507677,0.360351,0.355140
5,2,1,0.453013,0.455944,0.322762,0.322034
6,2,2,0.560817,0.565397,0.388528,0.453782
7,2,3,0.552024,0.527936,0.359479,0.392857
8,2,4,0.538846,0.538198,0.363386,0.347826
9,2,5,0.515168,0.504070,0.349784,0.480000
10,3,1,0.535538,0.526287,0.365377,0.430769
11,3,2,0.410881,0.442114,0.303719,0.412121
12,3,3,0.454296,0.464004,0.319491,0.373134
13,3,4,0.411857,0.424436,0.308849,0.395062
14,3,5,0.615797,0.541620,0.421573,0.388350
15,4,1,0.565946,0.556787,0.387568,0.422018
16,4,2,0.462722,0.500733,0.310605,0.309278
17,4,3,0.500550,0.529035,0.345265,0.360000
18,4,4,0.515168,0.512579,0.351235,0.358491
19,4,5,0.530522,0.519793,0.367749,0.416000
20,5,1,0.583532,0.573182,0.393103,0.492754
21,5,2,0.574464,0.602583,0.397460,0.511628
22,5,3,0.559443,0.530317,0.374111,0.449275
23,5,4,0.586940,0.565853,0.399599,0.489209
24,5,5,0.496393,0.516833,0.333821,0.456376

In [5]:
df_inner_cv_results

,repeat,outer_fold,inner_best_score,inner_best_params,n_candidates
0,1,1,0.565704,{'classifier__ccp_alpha': np.float64(3.0098543...,10000
1,1,2,0.593338,{'classifier__ccp_alpha': np.float64(0.0006286...,10000
2,1,3,0.574835,{'classifier__ccp_alpha': np.float64(6.7531301...,10000
3,1,4,0.575066,{'classifier__ccp_alpha': np.float64(0.0020472...,10000
4,1,5,0.580193,{'classifier__ccp_alpha': np.float64(0.0004520...,10000
5,2,1,0.580919,{'classifier__ccp_alpha': np.float64(3.2430611...,10000
6,2,2,0.565895,{'classifier__ccp_alpha': np.float64(9.1733859...,10000
7,2,3,0.596795,{'classifier__ccp_alpha': np.float64(5.1322528...,10000
8,2,4,0.564150,{'classifier__ccp_alpha': np.float64(0.0084842...,10000
9,2,5,0.590212,{'classifier__ccp_alpha': np.float64(0.0044571...,10000
10,3,1,0.568332,{'classifier__ccp_alpha': np.float64(1.5977326...,10000
11,3,2,0.589968,{'classifier__ccp_alpha': np.float64(1.3386896...,10000
12,3,3,0.590555,{'classifier__ccp_alpha': np.float64(0.0101309...,10000
13,3,4,0.601883,{'classifier__ccp_alpha': np.float64(4.2913607...,10000
14,3,5,0.556397,{'classifier__ccp_alpha': np.float64(1.1443740...,10000
15,4,1,0.569697,{'classifier__ccp_alpha': np.float64(0.0063428...,10000
16,4,2,0.558495,{'classifier__ccp_alpha': np.float64(0.0006145...,10000
17,4,3,0.582480,{'classifier__ccp_alpha': np.float64(0.0011594...,10000
18,4,4,0.593112,{'classifier__ccp_alpha': np.float64(0.0063130...,10000
19,4,5,0.570443,{'classifier__ccp_alpha': np.float64(1.8733235...,10000
20,5,1,0.586546,{'classifier__ccp_alpha': np.float64(1.4405899...,10000
21,5,2,0.560305,{'classifier__ccp_alpha': np.float64(0.0072770...,10000
22,5,3,0.584826,{'classifier__ccp_alpha': np.float64(7.8502125...,10000
23,5,4,0.562305,{'classifier__ccp_alpha': np.float64(0.0036363...,10000
24,5,5,0.598748,{'classifier__ccp_alpha': np.float64(3.5582144...,10000

In [6]:
df_results

,fit_time,score_time,test_roc_auc,test_balanced_accuracy,test_average_precision,test_f1_score,best_params
0,8311.690760,0.011846,0.615797,0.541620,0.421573,0.388350,{'classifier__ccp_alpha': np.float64(3.0098543...
1,8315.972574,0.011540,0.594523,0.556787,0.407297,0.422018,{'classifier__ccp_alpha': np.float64(0.0006286...
2,8317.163237,0.012147,0.586940,0.565853,0.399599,0.489209,{'classifier__ccp_alpha': np.float64(6.7531301...
3,8271.553582,0.011461,0.583532,0.573182,0.393103,0.492754,{'classifier__ccp_alpha': np.float64(0.0020472...
4,8072.354448,0.012807,0.580601,0.542224,0.414754,0.410714,{'classifier__ccp_alpha': np.float64(0.0004520...
5,8281.393547,0.011590,0.574464,0.602583,0.397460,0.511628,{'classifier__ccp_alpha': np.float64(3.2430611...
6,8581.906807,0.013005,0.565946,0.556787,0.387568,0.422018,{'classifier__ccp_alpha': np.float64(9.1733859...
7,8273.132247,0.011631,0.560817,0.565397,0.388528,0.453782,{'classifier__ccp_alpha': np.float64(5.1322528...
8,8247.586082,0.011558,0.559443,0.530317,0.374111,0.449275,{'classifier__ccp_alpha': np.float64(0.0084842...
9,8228.675743,0.011573,0.552024,0.527936,0.359479,0.392857,{'classifier__ccp_alpha': np.float64(0.0044571...
10,8316.175344,0.011561,0.538846,0.538198,0.363386,0.347826,{'classifier__ccp_alpha': np.float64(1.5977326...
11,8247.818687,0.011567,0.535538,0.526287,0.365377,0.430769,{'classifier__ccp_alpha': np.float64(1.3386896...
12,8270.834949,0.011591,0.530522,0.519793,0.367749,0.416000,{'classifier__ccp_alpha': np.float64(0.0101309...
13,8296.863016,0.011497,0.530059,0.494081,0.362718,0.316832,{'classifier__ccp_alpha': np.float64(4.2913607...
14,8337.923273,0.013260,0.518868,0.507677,0.360351,0.355140,{'classifier__ccp_alpha': np.float64(1.1443740...
15,8315.172521,0.011960,0.515168,0.512579,0.351235,0.358491,{'classifier__ccp_alpha': np.float64(0.0063428...
16,8287.270927,0.011527,0.515168,0.504070,0.349784,0.480000,{'classifier__ccp_alpha': np.float64(0.0006145...
17,8585.192608,0.012224,0.511632,0.485345,0.345060,0.330275,{'classifier__ccp_alpha': np.float64(0.0011594...
18,8254.553572,0.011599,0.500550,0.529035,0.345265,0.360000,{'classifier__ccp_alpha': np.float64(0.0063130...
19,8504.777805,0.012237,0.496393,0.516833,0.333821,0.456376,{'classifier__ccp_alpha': np.float64(1.8733235...
20,8383.584920,0.011494,0.462722,0.500733,0.310605,0.309278,{'classifier__ccp_alpha': np.float64(1.4405899...
21,8413.384701,0.012872,0.454296,0.464004,0.319491,0.373134,{'classifier__ccp_alpha': np.float64(0.0072770...
22,8334.440590,0.012090,0.453013,0.455944,0.322762,0.322034,{'classifier__ccp_alpha': np.float64(7.8502125...
23,8107.912868,0.011758,0.411857,0.424436,0.308849,0.395062,{'classifier__ccp_alpha': np.float64(0.0036363...
24,8369.008487,0.011495,0.410881,0.442114,0.303719,0.412121,{'classifier__ccp_alpha': np.float64(3.5582144...

In [7]:
lst = []
df = pd.DataFrame([eval(df_results['best_params'][0])], index=[0])
for i in range(len(df_results)-1):
    df_temp = pd.DataFrame([eval(df_results['best_params'][i+1])], index=[i+1])
    df = pd.concat([df, df_temp])
df

,classifier__ccp_alpha,classifier__max_depth,classifier__max_features,classifier__min_samples_leaf,classifier__min_samples_split,oversampling__k_neighbors
0,0.000030,11,sqrt,0.027707,0.088331,7
1,0.000629,6,sqrt,0.022650,0.219956,5
2,0.000007,9,sqrt,0.016245,0.081457,4
3,0.002047,6,None,0.096710,0.210646,6
4,0.000452,16,log2,0.018506,0.086778,6
5,0.000032,8,sqrt,0.032744,0.119249,6
6,0.000009,17,None,0.035062,0.102620,4
7,0.000005,6,sqrt,0.049115,0.220832,4
8,0.008484,10,sqrt,0.047797,0.320103,4
9,0.004457,7,sqrt,0.051807,0.399933,7
10,0.000016,8,None,0.013408,0.061078,3
11,0.000013,5,sqrt,0.046458,0.298193,6
12,0.010131,11,log2,0.086009,0.067261,3
13,0.000043,4,log2,0.042730,0.369690,5
14,0.000011,11,sqrt,0.033934,0.152738,6
15,0.006343,13,None,0.073246,0.223093,7
16,0.000615,17,None,0.016256,0.079302,7
17,0.001159,13,sqrt,0.070106,0.295964,5
18,0.006313,10,sqrt,0.039410,0.075882,5
19,0.000002,5,sqrt,0.028434,0.155499,7
20,0.000001,18,log2,0.023643,0.249771,3
21,0.007277,12,None,0.073213,0.228652,6
22,0.000008,11,None,0.024382,0.181946,6
23,0.003636,4,log2,0.050546,0.064504,5
24,0.000036,3,None,0.080658,0.060773,6